development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: insta_development
  pool: 5
  username: instauser
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: insta_test
  pool: 5
  username: instauser
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: insta_production
  pool: 5
  username: instauser
  password: password
  host: localhost